{
 "title": "Metricas CPU",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Metricas CPU & MEMORY",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "poyry",
     "rawSql": "SELECT\r\n    UNIX_TIMESTAMP(recvTime) as \"time\",\r\n    attrName as \"name\",\r\n    CAST(attrValue as decimal) as \"valor\"\r\nFROM `urn_ngsi-ld_Server_001_Computer`\r\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    UNIX_TIMESTAMP(recvTime) as \"time\",\r\n    attrName as \"name\",\r\n    CAST(attrValue as decimal) as \"valor\"\r\nFROM `urn_ngsi-ld_Server_001_Computer`\r\nWHERE attrName = \"cpu\"\r\nORDER BY \"time\" \r\n"
    }
   ]
  },
  {
   "title": "Memória",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    UNIX_TIMESTAMP(recvTime) as \"time\",\r\n    attrName as \"name\",\r\n    CAST(attrValue as decimal) as \"valor\"\r\nFROM `urn_ngsi-ld_Server_001_Computer`\r\nWHERE attrName = \"memory\"\r\nORDER BY \"time\" "
    }
   ]
  }
 ]
}