{
 "title": "Metricas",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Metricas CPU & MEMORY",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "poyry",
     "rawSql": "SELECT\r\n    UNIX_TIMESTAMP(recvTime) as \"time\",\r\n    attrName as \"name\",\r\n    CAST(attrValue as decimal) as \"valor\"\r\nFROM `urn_ngsi-ld_Server_001_Computer`\r\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    UNIX_TIMESTAMP(recvTime) as \"time\",\r\n    attrName as \"name\",\r\n    CAST(attrValue as decimal) as \"valor\"\r\nFROM `urn_ngsi-ld_Server_001_Computer`\r\nWHERE attrName = \"cpu\"\r\nORDER BY \"time\" \r\n"
    }
   ]
  },
  {
   "title": "Memória",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    UNIX_TIMESTAMP(recvTime) as \"time\",\r\n    attrName as \"name\",\r\n    CAST(attrValue as decimal) as \"valor\"\r\nFROM `urn_ngsi-ld_Server_001_Computer`\r\nWHERE attrName = \"memory\"\r\nORDER BY \"time\" "
    }
   ]
  },
  {
   "title": "Temperatura Ambiente C°",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    UNIX_TIMESTAMP(recvTime) as \"time\",\r\n    attrName as \"name\",\r\n    CAST(attrValue as decimal) as \"temp\"\r\nFROM `urn_ngsi-ld_Station_001_Weather`\r\nWHERE attrName = \"temp\"\r\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Umidade Relativa do Ar",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    UNIX_TIMESTAMP(recvTime) as \"time\",\r\n    attrName as \"name\",\r\n    CAST(attrValue as decimal) as \"humidity\"\r\nFROM `urn_ngsi-ld_Station_001_Weather`\r\nWHERE attrName = \"humidity\"\r\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Velocidade do Vento",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    UNIX_TIMESTAMP(recvTime) as \"time\",\r\n    attrName as \"atributo\",\r\n    CAST(attrValue as decimal) as \"valores\"\r\nFROM `urn_ngsi-ld_Station_001_Weather`\r\nWHERE attrName = \"windspeed\"\r\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Direção do Vento",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    UNIX_TIMESTAMP(recvTime) as \"time\",\r\n    attrName as \"Atributo\",\r\n    CAST(attrValue as decimal) as \"Valores\"\r\nFROM `urn_ngsi-ld_Station_001_Weather`\r\nWHERE attrName = \"winddirection\"\r\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Detalhes",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n    UNIX_TIMESTAMP(recvTime) as \"time\",\r\n    attrName as \"Atributo\",\r\n    attrValue as \"Valores\"\r\nFROM `urn_ngsi-ld_Station_001_Weather`\r\nWHERE attrName = \"description\"\r\nORDER BY \"time\""
    }
   ]
  },
  {
   "title": "Nuvens",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n    UNIX_TIMESTAMP(recvTime) as \"time\",\r\n    attrName as \"Atributo\",\r\n    CAST(attrValue as decimal) as \"Valores\"\r\nFROM `urn_ngsi-ld_Station_001_Weather`\r\nWHERE attrName = \"clouds\"\r\nORDER BY \"time\""
    }
   ]
  }
 ]
}